trigger:
  batch: true
  branches:
    include:
      - "*"
pr: none
pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: azure
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'